/**
 * Getting findings OUT.
 *
 * Everything the app produces has lived and died inside one tab. A tool whose
 * product is understanding needs a way to hand that understanding to someone
 * else — a report you can paste into a PR, a map you can put in a doc.
 */

export function download(filename, content, type = 'text/markdown') {
  const blob = content instanceof Blob ? content : new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  // Revoking immediately can cancel the download in some browsers; one frame
  // is enough for the click to have been handled.
  requestAnimationFrame(() => URL.revokeObjectURL(url));
}

const rel = (r) => r.replace(/_/g, ' ');

/** Insights -> a markdown report. */
export function insightsMarkdown(corpusName, insights, layout) {
  const L = [];
  L.push(`# ${corpusName} — code map report`, '');
  L.push(`${insights.totals.nodes.toLocaleString()} entities · ` +
    `${insights.totals.callables} callables · ` +
    `${insights.totals.communities} subsystems`, '');
  L.push(`Generated by Grapheon from ${layout?.meta?.source ?? 'the graph'} on ` +
    `${new Date().toISOString().slice(0, 10)}.`, '');

  L.push('## Most depended-upon', '');
  L.push('| Entity | Used by | File |', '|---|---:|---|');
  for (const h of insights.hubs) L.push(`| \`${h.label}\` | ${h.count} | ${h.path} |`);
  L.push('');

  L.push('## Reaches across subsystems', '');
  if (!insights.coupling.length) L.push('_Nothing spans more than one subsystem._', '');
  else {
    L.push('| Entity | Subsystems | Into |', '|---|---:|---|');
    for (const c of insights.coupling) {
      L.push(`| \`${c.label}\` | ${c.reaches} | ${c.into.join(', ')} |`);
    }
    L.push('');
  }

  L.push('## Dependency cycles', '');
  if (!insights.cycles.length) L.push('_None found._', '');
  else {
    for (const cyc of insights.cycles) {
      L.push(`- ${cyc.map((n) => `\`${n.label}\``).join(' → ')} → …`);
    }
    L.push('');
  }

  L.push('## Possibly unused', '');
  L.push(`${insights.unused.likelyTotal} callables have no inbound reference. ` +
    `A further ${insights.unused.entryPointTotal} look like framework entry ` +
    `points or runtime hooks and are listed separately — they are called by ` +
    `something the parser cannot see, so treating them as dead would be wrong.`, '');
  if (insights.unused.likely.length) {
    L.push('| Entity | File |', '|---|---|');
    for (const u of insights.unused.likely) L.push(`| \`${u.label}\` | ${u.path}:${u.line ?? ''} |`);
    L.push('');
  }
  if (insights.unused.entryPoints.length) {
    L.push('<details><summary>Entry points and hooks (excluded)</summary>', '');
    for (const u of insights.unused.entryPoints) L.push(`- \`${u.label}\` — ${u.why} — ${u.path}`);
    L.push('', '</details>', '');
  }

  return L.join('\n');
}

/** A blast-radius result -> a markdown report, suitable for pasting in a PR. */
export function blastMarkdown(corpusName, roots, rings, direction, depth, nodeById) {
  const total = rings.reduce((a, [, items]) => a + items.length, 0);
  const uncertain = rings.flatMap(([, i]) => i).filter((i) => !i.certain).length;
  const L = [];

  L.push(`# Impact of changing ${roots.length} entit${roots.length === 1 ? 'y' : 'ies'}`, '');
  L.push(`**${total}** ${direction === 'in' ? 'affected' : 'depended on'} within ${depth} hop${depth > 1 ? 's' : ''} — ${corpusName}.`, '');
  L.push('Starting from:', '');
  for (const r of roots) L.push(`- \`${r.l}\`${r.a?.path ? ` — ${r.a.path}` : ''}`);
  L.push('');

  if (uncertain) {
    L.push(`> ${uncertain} of these are reached only through an **inferred** edge — ` +
      `resolved by analysis rather than read from the source, so treat them as ` +
      `possible rather than certain.`, '');
  }

  for (const [d, items] of rings) {
    L.push(`## ${d === 1 ? 'Direct' : `${d} hops`} (${items.length})`, '');
    for (const it of items) {
      const n = nodeById.get(it.id);
      L.push(`- \`${n?.l ?? it.id}\`${n?.a?.path ? ` — ${n.a.path}` : ''}` +
        `${it.via ? ` _(${rel(it.via)})_` : ''}${it.certain ? '' : ' **inferred**'}`);
    }
    L.push('');
  }
  return L.join('\n');
}

/**
 * The Atlas as a PNG.
 *
 * Uses Pixi's extract API, which re-renders into a render texture. Reading the
 * canvas back directly does NOT work — without `preserveDrawingBuffer` the
 * WebGL buffer is already cleared by the time you could sample it, and you get
 * a blank image with no error.
 */
export async function mapPng(renderer) {
  if (!renderer?.app || !renderer.viewport) throw new Error('The map is not ready.');
  const canvas = renderer.app.renderer.extract.canvas(renderer.viewport);
  const blob = await new Promise((res, rej) => {
    if (canvas.convertToBlob) res(canvas.convertToBlob({ type: 'image/png' }));
    else canvas.toBlob((b) => (b ? res(b) : rej(new Error('Could not read the map.'))), 'image/png');
  });
  return blob;
}
